### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by dwlsalmeida**
Addresses #43,  #42, #35, #38, #36

### CODE REVIEW

**Comment by dwlsalmeida** [comment]
47075c0 improves the score to 140 here

**Comment by Gnurou** [comment]
Applied most of the changes so far, except the PPS ones that I want to look a bit closer. I'll also need to rebase after wrapping the Pps into an Rc anyway.

**Comment by Gnurou** [comment]
Also re: `try to parse PPS again on error`, it is nice to be able to recover in such cases, but if the stream is decidedly invalid, do we want to support it?

**Comment by dwlsalmeida** [comment]
Hi Alex, ended up forgetting before going on vacation, will check this first thing when I come back, sorry

**Comment by dwlsalmeida** [comment]
@Gnurou Hi Alex, this looks good to me!

>Also re: try to parse PPS again on error, it is nice to be able to recover in such cases, but if the stream is decidedly invalid, do we want to support it?

We can drop that. I agree, we shouldn't complicate things to help malformed streams

**Comment by Gnurou** [comment]
Thanks, based on your latest comment I have merged

```
decoders: h264: possibly renegotiate on every picture
decoders: h264: process PPS even in AwaitingStreamInfo|Reset
```

and will skip `decoders: h264: try to parse PPS again on error`.

I am wondering about `decoders: h264: check that first_mb_in_slice increases monotonically`. The `assert` statements could make the decoder process crash if an invalid stream is passed. This is something we ultimately want to avoid. Also what is the potential harm of such streams? Would going on open the potential for a vulnerability, or does it just mean the decoded output might be temporarily incorrect?

**Comment by dwlsalmeida** [comment]
@Gnurou as we discussed during our biweekly meeting, this will only temporarily corrupt the decoding of the stream. In particular, streams not conforming to the above will not be decoded by VA-API, as it does not support FMO:

https://en.wikipedia.org/wiki/Flexible_Macroblock_Ordering

Do you want me to return Err instead?

**Comment by Gnurou** [comment]
I have merged `decoders: h264: check that first_mb_in_slice increases monotonically`, after replacing the `assert` by a runtime warning so letting the decoder try to recover. While we should not crash on invalid input, it is still a good idea to report it.

With this all the CLs from the PR are merged, so let me close it. Thanks!

**Pull request closed without merging**
